const NOTIFICATION_TYPES = {
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_COMMENT: "TASK_COMMENT",
  TASK_DEADLINE: "TASK_DEADLINE",
  ADMIN_UPDATE: "ADMIN_UPDATE",
  WORKSPACE_JOIN_REQUEST: "WORKSPACE_JOIN_REQUEST",
};

module.exports = { NOTIFICATION_TYPES };
